FROM node:20-alpine

WORKDIR /app

RUN npm config set registry https://npmreg.proxy.ustclug.org/ && \
    npm config set disturl https://mirrors.ustc.edu.cn/node/ && \
    apk add --no-cache tzdata && \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone

EXPOSE 8101

CMD ["sh", "-c", "npm install && npm run dev"]
